# Generated by Django 4.2 on 2023-04-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='user_id',
            field=models.CharField(max_length=120),
        ),
    ]
